# Generated by Django 3.2.5 on 2023-01-18 04:12

from django.db import migrations

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from datetime import datetime, timedelta
import time

def beginning(apps, schema_editor):
    
    # Суперпользователь id-1
    user = User.objects.create_superuser(username='root',
    first_name = 'Суперпользователь',
    email='kazbek_kadirov@mail.ru',
    password='SsNn5678+-@', 
    last_login=datetime.now())
    print("Суперпользователь создан")
    
    # Группа менеджеров
    managers = Group.objects.get_or_create(name = 'Managers')
    managers = Group.objects.get(name='Managers')
    print("Группа менеджеров создана")
    
    # Пользователь с ролью менеджера id2
    user = User.objects.create_user(username='manager', password='Ss0066+-', email='manager@mail.ru', first_name='Менеджер', last_name='', last_login=datetime.now())
    managers.user_set.add(user)
    print("Менеджер добавлен в группу менеджеров")

    # Простые пользователи id3-12
    user = User.objects.create_user(username='user1', password='Uu0066+-', email='user1@mail.ru', first_name='Дина', last_name='Мусина', last_login=datetime.now())
    user = User.objects.create_user(username='user2', password='Uu0066+-', email='user2@mail.ru', first_name='Адия', last_name='Жунусова', last_login=datetime.now())
    user = User.objects.create_user(username='user3', password='Uu0066+-', email='user3@mail.ru', first_name='Айнура', last_name='Кенина', last_login=datetime.now())
    user = User.objects.create_user(username='user4', password='Uu0066+-', email='user4@mail.ru', first_name='Рустем', last_name='Какимов', last_login=datetime.now())
    user = User.objects.create_user(username='user5', password='Uu0066+-', email='user5@mail.ru', first_name='Алишер', last_name='Кабдуалиев', last_login=datetime.now())
    user = User.objects.create_user(username='user6', password='Uu0066+-', email='user6@mail.ru', first_name='Бауржан', last_name='Арыкбаев', last_login=datetime.now())
    user = User.objects.create_user(username='user7', password='Uu0066+-', email='user7@mail.ru', first_name='Кайрат', last_name='Танатаров', last_login=datetime.now())
    user = User.objects.create_user(username='user8', password='Uu0066+-', email='user8@mail.ru', first_name='Мерует', last_name='Искакова', last_login=datetime.now())
    user = User.objects.create_user(username='user9', password='Uu0066+-', email='user9@mail.ru', first_name='Ольга', last_name='Муравьева', last_login=datetime.now())
    user = User.objects.create_user(username='user10', password='Uu0066+-', email='user10@mail.ru', first_name='Ақжарқын', last_name='Сансызбаева', last_login=datetime.now())
  
    ###### Персона (человек) #####
    Person = apps.get_model("marriage", "Person")
    
    person = Person()
    person.user_id = 3
    person.sex = 'Ж'
    person.birthday = '2001-01-01 00:00:00'
    person.nationality = "Казашка"
    person.marital_status = "Не замужем"
    person.country = "Казахстан"
    person.city = "Алматы"
    person.amount_of_children = 0    
    person.height = 0    
    person.weight = 0    
    person.save()

    person = Person()
    person.user_id = 4
    person.sex = 'Ж'
    person.birthday = '2000-02-02 00:00:00'
    person.nationality = "Казашка"
    person.marital_status = "Не замужем"
    person.country = "Казахстан"
    person.city = "Астана"
    person.amount_of_children = 0  
    person.height = 0    
    person.weight = 0        
    person.save()

    person = Person()
    person.user_id = 5
    person.sex = 'Ж'
    person.birthday = '2000-03-03 00:00:00'
    person.nationality = "Казашка"
    person.marital_status = "Не замужем"
    person.country = "Казахстан"
    person.city = "Алматы"
    person.amount_of_children = 0  
    person.height = 0    
    person.weight = 0        
    person.save()

    person = Person()
    person.user_id = 6
    person.sex = 'М'
    person.birthday = '2001-04-04 00:00:00'
    person.nationality = "Казах"
    person.marital_status = "Холост"
    person.country = "Казахстан"
    person.city = "Алматы"
    person.amount_of_children = 0   
    person.height = 0    
    person.weight = 0        
    person.save()

    person = Person()
    person.user_id = 7
    person.sex = 'М'
    person.birthday = '2000-05-05 00:00:00'
    person.nationality = "Казах"
    person.marital_status = "Холост"
    person.country = "Казахстан"
    person.city = "Алматы"
    person.amount_of_children = 0 
    person.height = 0    
    person.weight = 0        
    person.save()

    person = Person()
    person.user_id = 8
    person.sex = 'М'
    person.birthday = '2001-06-06 00:00:00'
    person.nationality = "Казах"
    person.marital_status = "Холост"
    person.country = "Казахстан"
    person.city = "Астана"
    person.amount_of_children = 0    
    person.height = 0    
    person.weight = 0        
    person.save()

    person = Person()
    person.user_id = 9
    person.sex = 'М'
    person.birthday = '2000-07-07 00:00:00'
    person.nationality = "Казах"
    person.marital_status = "Холост"
    person.country = "Казахстан"
    person.city = "Астана"
    person.amount_of_children = 0    
    person.height = 0    
    person.weight = 0        
    person.save()
    
    person = Person()
    person.user_id = 10
    person.sex = 'Ж'
    person.birthday = '2001-08-08 00:00:00'
    person.nationality = "Казашка"
    person.marital_status = "Не замужем"
    person.country = "Казахстан"
    person.city = "Астана"
    person.amount_of_children = 0    
    person.height = 0    
    person.weight = 0        
    person.save()
    
    person = Person()
    person.user_id = 11
    person.sex = 'Ж'
    person.birthday = '2000-09-09 00:00:00'
    person.nationality = "Казашка"
    person.marital_status = "Не замужем"
    person.country = "Казахстан"
    person.city = "Алматы"
    person.amount_of_children = 0   
    person.height = 0    
    person.weight = 0        
    person.save()
    
    person = Person()
    person.user_id = 12
    person.sex = 'Ж'
    person.birthday = '2001-10-10 00:00:00'
    person.nationality = "Казашка"
    person.marital_status = "Не замужем"
    person.country = "Казахстан"
    person.city = "Алматы"
    person.amount_of_children = 0    
    person.height = 0    
    person.weight = 0        
    person.save()

    print("Персоны созданы")

    ##### Статус #####
    Status = apps.get_model("marriage", "Status")
    
    status = Status()
    status.person_id = 1
    status.dates = datetime.now()
    status.title = 'Верить в Ислам – вот с чего начинается путь разумного человека' 
    status.save()

    status = Status()
    status.person_id = 2
    status.dates = datetime.now()
    status.title = 'Аллах не испытывает нас. В любом случае, он учит жизни…' 
    status.save()

    status = Status()
    status.person_id = 3
    status.dates = datetime.now()
    status.title = 'Чем дальше ты отдаляешься от запретного, тем ближе становишься к Имаму' 
    status.save()

    status = Status()
    status.person_id = 4
    status.dates = datetime.now()
    status.title = 'Если тебе разбивают сердце или обижают как либо ещё, молись. Молись, и будет тебе счастье.' 
    status.save()

    status = Status()
    status.person_id = 5
    status.dates = datetime.now()
    status.title = 'Каждый намаз – это скрытая милостыня.' 
    status.save()

    print("Созданы статусы")

    ##### Сообщения #####
    Message = apps.get_model("marriage", "Message")
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=10)
    message.sender_id = 3
    message.recipient_id = 4
    message.details = 'Привет, Адия' 
    message.save()

    time.sleep(1)
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=9)
    message.sender_id = 4
    message.recipient_id = 3
    message.details = 'Привет, Дина!' 
    message.save()

    time.sleep(1)
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=8)
    message.sender_id = 3
    message.recipient_id = 4
    message.details = 'Как дела?' 
    message.save()

    time.sleep(1)

    message = Message()
    message.datem = datetime.now() - timedelta(minutes=7)
    message.sender_id = 4
    message.recipient_id = 3
    message.details = 'Спасибо, все хорошо. Сами как?' 
    message.save()

    time.sleep(1)
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=6)
    message.sender_id = 3
    message.recipient_id = 5
    message.details = 'Привет, Айнура' 
    message.save()

    time.sleep(1)
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=5)
    message.sender_id = 5
    message.recipient_id = 3
    message.details = 'Приветcтвую Вас, Дина' 
    message.save()

    time.sleep(1)
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=4)
    message.sender_id = 3
    message.recipient_id = 5
    message.details = 'Как дела, ребята подъехали?' 
    message.save()

    time.sleep(1)

    message = Message()
    message.datem = datetime.now() - timedelta(minutes=3)
    message.sender_id = 5
    message.recipient_id = 3
    message.details = 'Пока нет, ждем' 
    message.save()

    time.sleep(1)

    message = Message()
    message.datem = datetime.now() - timedelta(minutes=3)
    message.sender_id = 6
    message.recipient_id = 7
    message.details = 'Добрый день, Алишер' 
    message.save()

    time.sleep(1)

    message = Message()
    message.datem = datetime.now() - timedelta(minutes=3)
    message.sender_id = 7
    message.recipient_id = 6
    message.details = 'Добрый день, Рустем' 
    message.save()

class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(beginning),  
    ]
